name: 🚀 Auto Deploy Backend (Main Branch)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🔧 Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: ⏬ Checkout code
        uses: actions/checkout@v3

      - name: 🔐 Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: 🚀 Deploy to Server
        run: |
          DIR="/var/www/backend"           # server directory
          BRANCH="main"                    # branch to deploy
          ENV_FILE=".env"                  # environment file
          PM2_PROCESS="backend"            # PM2 process name
          ENTRY_FILE="src/server.js"       # Node.js entry file

          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} "
            set -e
            echo '🔄 Switching to branch: ${BRANCH}'
            cd ${DIR} || exit 1
            git fetch origin
            git checkout ${BRANCH}
            git reset --hard origin/${BRANCH}

            echo '⚙️ Applying environment file...'
            if [ -f ${ENV_FILE} ]; then
              cp ${ENV_FILE} .env
            else
              echo '❌ Env file ${ENV_FILE} not found!'
              exit 1
            fi

            echo '📦 Installing dependencies...'
            npm install --omit=dev

            if [ -f package.json ] && grep -q 'build' package.json; then
              echo '🏗️ Running build...'
              npm run build
            else
              echo 'ℹ️ No build script defined.'
            fi

            echo '♻️ Restarting PM2 process: ${PM2_PROCESS}'
            pm2 restart ${PM2_PROCESS} || pm2 start ${ENTRY_FILE} --name ${PM2_PROCESS}

            echo '✅ Deployment to ${BRANCH} completed successfully.'
          "
